### ISSUE TITLE
Logout is not working properly

### ISSUE THREAD

**Issue by Shyam268** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#26] opened 2020-10-14 07:27 UTC
Packages Used:
   "msal": "^1.3.4",
    "@azure/msal-angular": "^1.0.0",
issue:
User cannot logout it struct at logout session page:
![image](https://user-images.githubusercontent.com/30112490/95956763-63baed00-0e1c-11eb-968b-8ec610106243.png)

Code to reproduce:
appsetting.json

```
{
  "appsettings":{
     "authentication":{
      "authority": "https://login.microsoftonline.com/tenentId",
      "clientId":"1112222-2232-235456-21311",
      "cacheLocation": "localStorage"
      },
      "Service1":{
         "url" : "https://localhost:5001",
         "scope"  : ["https://{mytenent}.onmicrosoft.com/1231-321313-13233311/CRUD"]
      },
      "redirectUri":"http://localhost:4200/",
      "postLogoutRedirectUri": "http://localhost:4200/",
  }
}
```
msalConfig.ts
```

export function MSALConfigFactory(config: AppConfigService): Configuration {
  const appSettings = config.getConfig(config.APP_SETTINGS);
  const authentication = appSettings.authentication;
  const auth = {
      auth: {
          clientId: authentication.clientId,
          authority: authentication.authority,
          redirectUri: appSettings.redirectUri,
          postLogoutRedirectUri: appSettings.postLogoutRedirectUri,
          navigateToLoginRequestUrl: true,
          validateAuthority: true,
      },
      cache: {
         cacheLocation: 'localStorage'
      }
  };
  return (auth as Configuration);
}
```
logoutComponet.ts
  logout() {
    this.authService.logout();
  }

app registration settings:

![image](https://user-images.githubusercontent.com/30112490/95956884-91a03180-0e1c-11eb-8116-f5567a69dda4.png)

i am able to call web api but logout not working properly

**Comment by derisen** [comment] 2020-10-14 23:36
@Shyam268 I was not able to reproduce this. Is there a specific browser that you're having this issue with? Any other details? Also, did you try updating your [msal.js](url) and [msal-angular](url) packages?

You shouldn't change your authority to [common](url) in the app if you registered your app as a single-tenant.

**Comment by derisen** [comment] 2020-10-14 23:38
Looks like the issue is being discussed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2422). Closing this as duplicate.

**Closed by derisen** 2020-10-14 23:38 UTC
